version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resize-image-function"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ur81pfbmjv8t"
s3_prefix = "resize-image-function"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
