version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-image-resize"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d68puvwir37m"
s3_prefix = "sam-image-resize"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
