version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-resize-image"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ab7w6hl6jqi5"
s3_prefix = "sam-resize-image"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
