AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-image-resize

  SAM Template for sam-image-resize

Globals:
  Function:
    Runtime: nodejs16.x
    Tracing: "Active"
    Timeout: 6
    MemorySize: 128

Resources:
  ImageUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "awesome-bucket-${AWS::AccountId}"

  ImageResizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/resize-image
      Handler: app.lambdaHandler
      Policies: AmazonS3FullAccess
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref ImageUploadBucket
            Events: s3:ObjectCreated:*
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - app.ts

Outputs:
  ImageResizeFunction:
    Description: "Resize Image Function ARN"
    Value: !GetAtt ImageResizeFunction.Arn
  ImageResizeFunctionIamRole:
    Description: "Implicit IAM Role created for ImageResizeFunction"
    Value: !GetAtt ImageResizeFunctionRole.Arn
  OutputBucketName:
    Description: "Output bucket name"
    Value: !Ref ImageUploadBucket
