version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-todo-list-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11yt5ssv42cku"
s3_prefix = "sam-todo-list-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
