AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-todo-list

  SAM Template for sam-todo-list

Globals:
  Function:
    Architectures:
      - x86_64
    MemorySize: 128
    Runtime: nodejs16.x
    Timeout: 30

Resources:
  GetAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/get-all-items.handler
      Description: HTTP get method to get all TODO items from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDbTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          SAMPLE_TABLE: !Ref DynamoDbTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

  PutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/put-item.handler
      Description: HTTP get method to update/create TODO item in DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDbTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref DynamoDbTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  DynamoDbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  GetAllToDoItemsFunction:
    Description: "Get all TODO items Function ARN"
    Value: !GetAtt GetAllItemsFunction.Arn
  GetAllToDoItemsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GetAllItemsFunctionRole.Arn
