version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "text-detection-workflow"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i5s0zdvy9w9y"
s3_prefix = "text-detection-workflow"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
