AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-step-function

  Sample SAM Template for sam-step-function

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs16.x
    Tracing: 'Active'


Resources:
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  DocumentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: DocumentID
        Type: String

  ExtractDocumentMetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/extract-document-metadata/
      Handler: index.handler

  GetTextDetectionResultsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/metadata-detection-results/
      Handler: index.handler
      Policies:
        - TextractPolicy: {}

  InsertDocumentMetadataIntoDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/insert-metadata-in-db/
      Handler: index.handler
      Environment:
        Variables:
          DYNAMO_DB_TABLE: !Ref DocumentTable
      Policies:
        - TextractPolicy: {}
        - DynamoDBWritePolicy:
            TableName: !Ref DocumentTable

  DocumentProcessingSM:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/document_processing.asl.json
      DefinitionSubstitutions:
        ExtractDocumentMetadataFunctionArn: !GetAtt ExtractDocumentMetadataFunction.Arn
        GetTextDetectionResultsFunctionArn: !GetAtt GetTextDetectionResultsFunction.Arn
        InsertDocumentMetadataIntoDBFunctionArn: !GetAtt InsertDocumentMetadataIntoDBFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ExtractDocumentMetadataFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GetTextDetectionResultsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref InsertDocumentMetadataIntoDBFunction
        - S3CrudPolicy:
            BucketName: 
              !Ref DocumentBucket
        - TextractPolicy: {}
      Events:
        DocumentUploadEvent: 
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "aws.s3"
              detail-type: 
                - "Object Created"
              detail:
                bucket:
                  name:
                    - !Ref DocumentBucket

Outputs:
  OutputBucketName:
    Description: "Output bucket name"
    Value: !Ref DocumentBucket
  DynomoDbTable:
    Description: "Dynamo table"
    Value: !Ref DocumentTable
